環境の問題点の修正
suzuka-kosen-festa/2022-server pull request #17
Opened 2022-08-03 09:50 UTC by Bayathy

間違えてevacuationブランチ消して、作業全部終えたpush後にPR立ってるもとがevacuationブランチだと気づきました。懺悔

## 何をしたか
- 環境の問題点の修正
- issue templateの追加

2022-08-03 09:55 UTC, Bayathy commented
PRで立ってた問題点は全部修正してるので、issue template以外は見なくて大丈夫です

2022-08-03 11:15 UTC, re-taro requested changes

2022-08-03 11:15 UTC, re-taro commented on .dockerignore
> +./dist
`.dockerignore`にはコンテナを作成するときに必要なもの以外すべてを省くことができます。また、それが推奨されているので省くべきです。

2022-08-03 11:48 UTC, Bayathy commented on .dockerignore
> +./dist
要はもっといらんファイル書き足せってことでいいっすか？それに関しては完全に失念してた

2022-08-03 11:50 UTC, Bayathy commented on .dockerignore
> +./dist
ていうかこれgitignoreと同じノリでdistファイルignoreしてるけど、これしちゃダメじゃね

2022-08-03 12:07 UTC, re-taro commented on .dockerignore
> +./dist
自己完結早いな。例えばeslintとかの設定ファイル群とかreadmeとかは、ある必要がないからねぇ

2022-08-09 10:21 UTC, Bayathy commented
Dockerfileの名前はなんか違う気がするので後々変えときます

2022-08-09 10:45 UTC, re-taro requested changes

2022-08-09 10:45 UTC, re-taro commented on .github/workflows/test.yml
> +         - master
```suggestion
         - main

```

2022-08-09 10:45 UTC, re-taro commented on .github/workflows/test.yml
> +         - master
```suggestion
         - main

```

2022-08-09 10:45 UTC, re-taro commented on .github/workflows/test.yml
> +   eslint:
eslintという名前のフロー内部で全部の処理がされている。
```suggestion
   なんか良さげな名前:

```

2022-08-09 10:45 UTC, re-taro commented on Dockerfile_build
> +FROM node:16-alpine
alpineイメージは依存がない場合があったりして動かない可能性があるため非推奨
```suggestion
FROM gcr.io/distroless/nodejs:16

```

2022-08-09 10:45 UTC, re-taro commented on Dockerfile_build
> +FROM node:16-alpine
ファイル生成や、書き込みがない場合はnonrootを使おう。

2022-08-09 10:45 UTC, re-taro commented on Dockerfile_build
> +COPY package*.json ./
不要なwildcardはセキュリティホールになりかねないのでやめましょう

```suggestion
COPY package.json ./

```

2022-08-09 10:45 UTC, re-taro commented on Dockerfile_build
> +COPY yarn.lock ./
このようにしてあげると記述が一行ですみます。
```suggestion
COPY package.json yarn.lock ./

```

2022-08-09 10:45 UTC, re-taro commented on Dockerfile_build
> +COPY . .
本番環境を想定している場合、マルチステージビルドをするなどすべきです。またこのイメージは依存関係を全部落としてその後プロジェクト全体をコピペしてるだけで終わっています。

2022-08-09 10:45 UTC, re-taro commented on Dockerfile_build
> +COPY . .
あくまで一例ですが...

```dockerfile
FROM node:16 AS build

WORKDIR /build

ENV NODE_ENV=development

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . ./
RUN yarn build

FROM node:16 AS deps

WORKDIR /deps

ENV NODE_ENV=production

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

FROM gcr.io/distroless/nodejs:16

WORKDIR /app

ENV NODE_ENV=production

COPY --from=build /build/dist /app/dist
COPY --from=deps /deps/node_modules /app/node_modules

CMD ["dist/main"]
```

2022-08-09 10:45 UTC, re-taro commented on test/app.e2e-spec.ts
> +
```suggestion
  afterAll(async () => {
    await app.close();
  });
```

2022-08-09 10:45 UTC, re-taro commented on test/app.e2e-spec.ts
> +
これはNestJSのテンプレが悪いんだけどこのままだとe2eテストがあまりよろしくない終了をするのでこれを追加しましょう。

2022-08-11 15:44 UTC, Bayathy commented
DockerFileあたりはベストプラクティスを読んで変更するかもしれないでworkflowsお願いします

2022-08-12 16:58 UTC, re-taro requested changes

2022-08-12 16:58 UTC, re-taro commented on .github/workflows/lint.yml
> +        run: yarn install --frozen-lockfile
--frozen-lockfileは非推奨

```suggestion
        run: yarn install --immutable

```

2022-08-12 16:58 UTC, re-taro commented on .github/workflows/test.yml
> +
setupを切り分けているがこれだとした2つが動かないので修正必須。

2022-08-12 16:58 UTC, re-taro commented on .github/workflows/test.yml
> +name: lint and test
lintは別workflowがあるから冗長なのでは

2022-08-12 16:58 UTC, re-taro commented on .github/workflows/test.yml
> +           run: yarn install --frozen-lockfile
--frozen-lockfileは非推奨
```suggestion
           run: yarn install --immutable

```

2022-08-12 16:58 UTC, re-taro commented on .github/workflows/test.yml
> +    eslint:
仮にわけれたとしてもこの書き方だとstepsがないから動かない

2022-08-12 16:58 UTC, re-taro commented on .github/workflows/test.yml
> +    test:
上に同じく

2022-08-12 16:58 UTC, re-taro commented on Dockerfiles/DevDockerfile
> +FROM gcr.io/distroless/nodejs:16
中身は書き換えられるはずだと思うので言及しないがファイル名は`*.Dockerfile`が好ましい。

2022-08-12 16:58 UTC, re-taro commented on Dockerfiles/ProdDockerfile
> +FROM node:16 AS build
ファイル名は`*.Dockerfile`が好ましい。

2022-08-12 16:58 UTC, re-taro commented on Dockerfiles/ProdDockerfile
> +RUN yarn install --frozen-lockfile
--frozen-lockfileは非推奨

```suggestion
RUN yarn install --immutable

```

2022-08-12 16:58 UTC, re-taro commented on Dockerfiles/ProdDockerfile
> +RUN yarn install --frozen-lockfile
--frozen-lockfileは非推奨

```suggestion
RUN yarn install --immutable

```

2022-08-12 18:33 UTC, Bayathy reviewed
深夜でコミット文終わってます。正しくは change:Dockerfileとdokcer-compose.yml の修正です

2022-08-12 18:33 UTC, Bayathy commented on Dockerfiles/ProdDockerfile
> +FROM node:16 AS build
[3bf56ea](https://github.com/suzuka-kosen-festa/2022-server/pull/17/commits/3bf56ea89bd7513008f9db0cbfdeee302735b2f1)

2022-08-12 18:33 UTC, Bayathy commented on .github/workflows/lint.yml
> +        run: yarn install --frozen-lockfile
[b74db77](https://github.com/suzuka-kosen-festa/2022-server/pull/17/commits/b74db7786a650752c3aee53763a2b87cfc42a70e)

2022-08-12 18:33 UTC, Bayathy commented on .github/workflows/test.yml
> +name: lint and test
[b74db77](https://github.com/suzuka-kosen-festa/2022-server/pull/17/commits/b74db7786a650752c3aee53763a2b87cfc42a70e)

2022-08-12 18:33 UTC, Bayathy commented on .github/workflows/test.yml
> +
[b74db77](https://github.com/suzuka-kosen-festa/2022-server/pull/17/commits/b74db7786a650752c3aee53763a2b87cfc42a70e)

2022-08-12 18:33 UTC, Bayathy commented on Dockerfiles/DevDockerfile
> +FROM gcr.io/distroless/nodejs:16
[3bf56ea](https://github.com/suzuka-kosen-festa/2022-server/pull/17/commits/3bf56ea89bd7513008f9db0cbfdeee302735b2f1)

2022-08-12 18:37 UTC, Bayathy commented on .github/workflows/test.yml
> +name: lint and test
今devで作業してしまっているので、状況に合わせておいてあります

2022-08-12 18:38 UTC, Bayathy commented on Dockerfiles/ProdDockerfile
> +RUN yarn install --frozen-lockfile
[422963e](https://github.com/suzuka-kosen-festa/2022-server/pull/17/commits/422963e739903f85a6c8ad602a2c4f22cfd0e2f5)

2022-08-12 18:38 UTC, Bayathy commented on Dockerfiles/ProdDockerfile
> +RUN yarn install --frozen-lockfile
[422963e](https://github.com/suzuka-kosen-festa/2022-server/pull/17/commits/422963e739903f85a6c8ad602a2c4f22cfd0e2f5)

2022-08-12 18:43 UTC, Bayathy commented
[422963e](https://github.com/suzuka-kosen-festa/2022-server/pull/17/commits/422963e739903f85a6c8ad602a2c4f22cfd0e2f5)
これ深夜で頭が終わってたのでコミット文が崩壊してるので訂正すると、"change:Dockerfilesの修正とdocker-composeの設定の追加"です

2022-08-12 18:48 UTC, Bayathy commented
```
RUN yarn install --production
```
か
```
ENV NODE_ENV=production
RUN yarn install
```
のどちらにするべきか

2022-09-07 12:50 UTC, re-taro requested changes

2022-09-07 12:50 UTC, re-taro commented on .github/workflows/lint.yml
> +           uses: stefanzweifel/git-auto-commit-action@v4
このactionsを使うとjobsが発火しないため自分で書きましょう

2022-09-07 12:50 UTC, re-taro commented on docker-compose.dev.yml
> +version: '3'
動作確認はされていますか？

2022-09-07 12:50 UTC, re-taro commented on Dockerfiles/dev.Dockerfile
> +FROM gcr.io/distroless/nodejs:16
これ開発用のコンテナで中で色々したいんだったらdistrolessは向いていないですよ。shellないし

2022-09-07 12:50 UTC, re-taro commented on docker-compose.prod.yml
> +web:
productionの時はsqlは外部のやつを使うんですっけ？

2022-09-15 09:06 UTC, re-taro requested changes

2022-09-15 09:06 UTC, re-taro commented on prisma/schema.prisma
> +// This is your Prisma schema file,
prismaのschemaがこれで合ってるかどうかの判断が私にはできないので
@Bayathy と @oonya で話し合って決めてください

2022-09-15 09:32 UTC, Bayathy commented on Dockerfiles/dev.Dockerfile
> +FROM node:16
コンテナ内のyarnをberryにあげるのがだるそうだったのでv1に戻しました

[6c1b134](https://github.com/suzuka-kosen-festa/2022-server/pull/17/commits/6c1b134deca44406e37ec477cff77e6e02683758)

2022-09-15 10:27 UTC, oonya reviewed
DB設計というか仕様漏れなのかなーって思うとこをレビューしました

2022-09-15 10:27 UTC, oonya commented on prisma/schema.prisma
> +  RealName      String
Student tableのRealNameカラムの名前が若干気になった
nicknameとの対比なんだろうけど単純にName, もしくは読み仮名なのを強調したい的な意図ならkanaとかの方が自然かなっておもた
まあ命名についてはよくわからんので別途相談してもらえれば

2022-09-15 10:27 UTC, oonya commented on prisma/schema.prisma
> +model Visitor {
> 家族の一人ひとりの学生との続柄と一日目と二日目のどちらに来るかを全員分入力してもらいます。

Visitor tableにこの情報ないとダメそう。

> (中学生は)答えてもらった内容をもとにQRコードを生成しメールで送信します

だそうなのでvisitor tableにemailカラム必要そう

2022-09-15 10:35 UTC, re-taro commented on Dockerfiles/dev.Dockerfile
> +FROM gcr.io/distroless/nodejs:16
普通にdebianとかで良いかと

2022-09-15 10:36 UTC, re-taro commented on .github/workflows/lint.yml
> +           uses: stefanzweifel/git-auto-commit-action@v4
検証されましたか？私の手元ではayuto commit後はwaitingとなってしまいCIが起動しません

2022-09-19 19:07 UTC, Bayathy commented
auto commitの部分のworkflowをHPと同じ処理にしてあります。それに合わせて発火元のworkflowのトリガーをpull requestに変更しました。
workflows_runはデフォルトブランチにないと動かないのでデバッグはできてないです　

2022-09-21 16:12 UTC, re-taro commented on .github/workflows/lint.yml
> +name: lint:fix
名前の変更をお願いします

2022-09-21 16:15 UTC, Bayathy commented on .github/workflows/lint.yml
> +name: lint:fix
変更理由教えてください

2022-09-21 16:22 UTC, Bayathy commented on .github/workflows/lint.yml
> +name: lint:fix
大体理解した、直します

2022-09-21 16:40 UTC, re-taro approved these changes

2022-09-21 19:11 UTC, merged