Studentのサービスを書いた
suzuka-kosen-festa/2022-server pull request #19
Opened 2022-09-23 12:47 UTC by Bayathy

ちょっと寝ぼけながらやってたときに開発環境の変更もしちゃってます。

バックエンドのテスト書くの初めてなのでおかしいところあったらいってください

2022-09-25 06:47 UTC, re-taro requested changes

2022-09-25 06:47 UTC, re-taro commented on prisma/schema.prisma
中学生の生徒の親を招待するときとOBの周りが不明確なので仕様にあげてください

2022-09-25 06:47 UTC, re-taro commented on src/app.module.ts
> -   providers: [AppService],
app.hogehogeはいらないので消去していいかと思います。代わりにhealthcheckを生やすなどを検討してください

2022-09-25 06:47 UTC, re-taro commented on src/prisma/prisma.service.ts
> +   }
これは質問なのですがOnModuleDestroyは非推奨になったんでしたっけ？
```ts
import { Injectable, OnModuleInit, OnModuleDestroy } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';

@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit, OnModuleDestroy {
  async onModuleInit() {
    await this.$connect();
  }

  async onModuleDestroy() {
    await this.$disconnect();
  }
}
```

2022-09-25 06:47 UTC, re-taro commented on src/prisma/prisma.service.ts
> +import { INestApplication, Injectable, OnModuleInit } from '@nestjs/common';
prisma.module.tsはどこですか

2022-09-25 06:47 UTC, re-taro commented on src/student/student.service.ts
> +      //値の返し方はQRコード読み取り側と相談したい
```suggestion
      //TODO: 値の返し方はQRコード読み取り側と相談したい
```

2022-09-25 06:47 UTC, re-taro commented on src/student/student.controller.ts
> +//'Body' is already defined as a built-in global variable. が出る
Where is Swagger

2022-09-25 06:47 UTC, re-taro commented on src/student/student.controller.ts
> +   @Get('getall')
これ/student/getallで取得になるけど普通に/studentで良くない？

2022-09-25 06:47 UTC, re-taro commented on src/student/student.controller.ts
> +   @Get('check/:uuid')
```suggestion
   @Get('/check/:uuid')
```

2022-09-25 06:47 UTC, re-taro commented on src/student/student.controller.ts
> +   @Post('create')
/studentにPOSTしたら作成されるというのは認識的におかしくないはずなので/student/createは冗長

2022-09-25 06:47 UTC, re-taro commented on src/student/student.controller.ts
> +   @Put('update')
/studentにPUTしたら更新されるというのは認識的におかしくないはずなので/student/updateは冗長

2022-09-25 06:48 UTC, re-taro requested changes
CIが一切走っていないがよろしいでしょうか？testとかはテストケースは見ましたが実際にそれで動作するかはわからないので走らせてもらいたいのですが

2022-09-25 09:17 UTC, Bayathy commented on prisma/schema.prisma
前それ統一するってMTGで言ってましたよ

2022-09-25 09:39 UTC, Bayathy commented on src/prisma/prisma.service.ts
> +   }
Prismaの独自のコネクション切断との兼ね合いでenableshatdownになってるだけです

2022-09-25 09:39 UTC, Bayathy commented on src/student/student.controller.ts
> +//'Body' is already defined as a built-in global variable. が出る
忘れ

2022-09-25 09:42 UTC, Bayathy commented on src/student/student.controller.ts
> +   @Get('getall')
多分その時は一意の生徒を取得するAPIを建てようと思ってたからその名残　修正します

2022-09-25 09:43 UTC, Bayathy commented
> CIが一切走っていないがよろしいでしょうか？testとかはテストケースは見ましたが実際にそれで動作するかはわからないので走らせてもらいたいのですが

2022-09-25 09:44 UTC, Bayathy commented
> CIが一切走っていないがよろしいでしょうか？testとかはテストケースは見ましたが実際にそれで動作するかはわからないので走らせてもらいたいのですが

走ってますよ

2022-09-25 09:51 UTC, Bayathy commented on src/student/student.controller.ts
> +   @Get('check/:uuid')
公式は(hoge/fuga)の記法で書いてるのでそっちに合わせてます

2022-09-25 10:05 UTC, re-taro commented
> CIが一切走っていないがよろしいでしょうか？testとかはテストケースは見ましたが実際にそれで動作するかはわからないので走らせてもらいたいのですが
> > 走ってますよ

失礼

2022-09-25 10:10 UTC, re-taro commented on prisma/schema.prisma
中学生の親についてはどういうふうに統一するかという資料などは残っていますか？OBについてはそうでしたね、アンケートに答えさせるとのことでしたが、それでしたらOB用のテーブルが必要じゃないですか？

2022-09-25 10:11 UTC, Bayathy commented on src/prisma/prisma.service.ts
> +   }
兼ね合いっていうのはModuleが削除される順番で公式が関与してるissue読んだ感じ、onModuleDestroyだとよくないっぽい

2022-09-25 10:16 UTC, Bayathy commented on prisma/schema.prisma
中学生の親は値を決め打ちするって話だったはずです
OBに関しては取る情報がまず決まってないのでなんとも言えないです

2022-09-25 10:16 UTC, re-taro commented on src/student/student.controller.ts
> +   @Get('getall')
治すか何か理由があるなら書いてからresolveしてください

2022-09-25 10:17 UTC, re-taro commented on src/student/student.controller.ts
> +   @Post('create')
治すか何か理由があるなら書いてからresolveしてください

2022-09-25 10:17 UTC, re-taro commented on src/student/student.controller.ts
> +   @Put('update')
治すか何か理由があるなら書いてからresolveしてください

2022-09-25 10:18 UTC, Bayathy commented on src/student/student.controller.ts
> +   @Get('getall')
まだプッシュしてないだけなんでちょっと待って

2022-09-25 10:22 UTC, Bayathy commented on src/app.module.ts
> -   providers: [AppService],
helthcheckは別ブランチでやります

2022-09-25 12:13 UTC, Bayathy commented on src/student/student.controller.ts
> +   @Put('update')
[87c8ae0](https://github.com/suzuka-kosen-festa/2022-server/pull/19/commits/87c8ae075cb6fc0f48ebab1c3923aae01898923d)

2022-09-25 12:13 UTC, Bayathy commented on src/student/student.controller.ts
> +   @Post('create')
[87c8ae0](https://github.com/suzuka-kosen-festa/2022-server/pull/19/commits/87c8ae075cb6fc0f48ebab1c3923aae01898923d)

2022-09-25 12:13 UTC, Bayathy commented on src/student/student.controller.ts
> +   @Get('getall')
[87c8ae0](https://github.com/suzuka-kosen-festa/2022-server/pull/19/commits/87c8ae075cb6fc0f48ebab1c3923aae01898923d)

2022-09-25 12:14 UTC, Bayathy commented on src/student/student.controller.ts
> +//'Body' is already defined as a built-in global variable. が出る
[99e5bc9](https://github.com/suzuka-kosen-festa/2022-server/pull/19/commits/99e5bc95e0fc59844b9f15ed707fec13a40f2792)

2022-09-25 12:14 UTC, Bayathy commented on src/prisma/prisma.service.ts
> +import { INestApplication, Injectable, OnModuleInit } from '@nestjs/common';
[5a9d5f2](https://github.com/suzuka-kosen-festa/2022-server/pull/19/commits/5a9d5f2eab5d78599ad1f21e0dbe7b6e933f22d8)

2022-09-26 15:04 UTC, re-taro requested changes

2022-09-26 15:04 UTC, re-taro commented on src/student/student.controller.ts
> +   }
```suggestion
   }
   
```

2022-09-27 10:24 UTC, merged