Prismaのhealth checkを書いた
suzuka-kosen-festa/2022-server pull request #32
Opened 2022-09-27 19:37 UTC by Bayathy

healthcheckなんもわからんので、なんかおかしいところとか足りないところあったら言ってください

2022-09-28 05:03 UTC, re-taro requested changes
reviewing

2022-09-28 05:04 UTC, re-taro commented
これPrismaのhealth checkはできてるけどHTTP接続できているかを確認する術になりうる？

2022-09-28 05:07 UTC, Bayathy commented
HealthcheckのHTTPのやつ勘違いしてたわ。言われて今気づいたからすぐ追加します。

2022-09-28 07:54 UTC, re-taro requested changes

2022-09-28 07:54 UTC, re-taro commented on src/health/health.controller.ts
> +      return this.health.check([() => this.httpHealth.pingCheck('httpHealth', 'https://docs.nestjs.com')]);
これ自身の状態を返せないのかな、このままだとdoc.nestjs.comとの通信を返すことになるけど

2022-09-28 07:54 UTC, re-taro commented on src/health/health.controller.spec.ts
> +   it('should be defined', () => {
testケースが適当すぎるかな。/health/db /health/httpからのレスポンスをstrictEqualとかで比較することをおすすめする

2022-09-28 07:55 UTC, Bayathy commented on src/health/health.controller.spec.ts
> +   it('should be defined', () => {
httpはできるけど、dbはできない
Httpの方は書きます

2022-09-28 07:56 UTC, Bayathy commented on src/health/health.controller.ts
> +      return this.health.check([() => this.httpHealth.pingCheck('httpHealth', 'https://docs.nestjs.com')]);
実際Healthcheckのドキュメント適当すぎてよくわかってないんやけど、これはサーバーがHttp通信をできることを見たいのか、サーバーがHttpのレスポンスを返せることを見たいのかどっちかわからん

2022-09-28 07:58 UTC, Bayathy commented on src/health/health.controller.spec.ts
> +   it('should be defined', () => {
でも実際のレスポンスはdocker建てんと見れんくないか

2022-09-28 07:59 UTC, re-taro commented on src/health/health.controller.ts
> +      return this.health.check([() => this.httpHealth.pingCheck('httpHealth', 'https://docs.nestjs.com')]);
うーん、前者が確認できることで後者も確認できる

2022-09-28 08:00 UTC, re-taro commented on src/health/health.controller.spec.ts
> +   it('should be defined', () => {
dbはできない気もする。どういう風にhealth check回ってるかわからんからなんとも言えん

2022-09-28 13:33 UTC, Bayathy commented on src/health/health.controller.ts
> +
これ逆に分けない書き方あるんですか

2022-09-28 13:36 UTC, Bayathy commented on src/health/health.controller.ts
> +
あーコンストラクタじゃなくて下の関数の部分か
それ配列で渡したら何故か空になるからやめた

2022-09-28 17:14 UTC, re-taro commented on src/health/health.controller.ts
> +
まじ？

2022-09-29 03:03 UTC, re-taro requested changes

2022-09-29 18:41 UTC, merged