Feature/#4
suzuka-kosen-festa/2022-server pull request #33
Opened 2022-10-05 23:12 UTC by Bayathy

Uuidの照合先はapp.serviceで受けてパースしてからからリダイレクトで処理します。その時にHistoryにタイムスタンプ押す処理するのでまだその二つは実装してないです。

2022-10-06 00:54 UTC, re-taro requested changes
moduleごとにpr分けろカス

2022-10-06 14:08 UTC, re-taro commented on src/guest/guest.controller.ts
> +   async checkuuid(@Param('uuid') id: string): Promise<Guest> {
nullの可能性はないのですか？

```suggestion
   async checkuuid(@Param('uuid') id: string): Promise<Guest | null> {
```

2022-10-06 14:20 UTC, re-taro commented on src/health/health.e2e-spec.ts
> +   beforeEach(async () => {
test/app.e2e-spec.tsもなんだけどこここれでいいよ
```suggestion
   beforeAll(async () => {
```

2022-10-06 14:20 UTC, re-taro commented on src/jhs/jhs.controller.spec.ts
> +   beforeEach(async () => {
これでいい

```suggestion
   beforeAll(async () => {
```

2022-10-06 14:21 UTC, re-taro commented on src/jhs/jhs.service.spec.ts
> +   beforeEach(async () => {
これでいい

```suggestion
   beforeAll(async () => {
```

2022-10-06 14:21 UTC, re-taro commented on src/ob/ob.controller.spec.ts
> +   beforeEach(async () => {
これでいいはずです

```suggestion
   beforeAll(async () => {
```

2022-10-06 14:22 UTC, re-taro commented on src/ob/ob.controller.spec.ts
> +
プロダクト全体を通してitかtestのどちらかに揃えてください

2022-10-06 14:23 UTC, re-taro commented on src/ob/ob.service.spec.ts
> +   beforeEach(async () => {
これで良い

```suggestion
   beforeAll(async () => {
```

2022-10-06 14:23 UTC, re-taro commented on src/ob/ob.service.spec.ts
> +
プロダクト全体を通してitかtestのどちらかに揃えてください

2022-10-06 14:24 UTC, re-taro commented on src/sponsor/sponsor.controller.spec.ts
> +   beforeEach(async () => {
これでいいはず

```suggestion
   beforeAll(async () => {
```

2022-10-06 14:24 UTC, re-taro commented on src/sponsor/sponsor.controller.spec.ts
> +
プロダクト全体を通してitかtestのどちらかに揃えてください

2022-10-06 14:24 UTC, re-taro commented on src/sponsor/sponsor.service.spec.ts
> +   beforeEach(async () => {
これで良い

```suggestion
   beforeAll(async () => {
```

2022-10-06 14:25 UTC, re-taro commented on src/student/entities/student.ts
> +import { GuestEntity } from '../../guest/entity/guest';
entityはディレクトリを分けるのも良いかも？これは提案

2022-10-06 14:28 UTC, Bayathy commented on src/guest/guest.controller.ts
> +   async checkuuid(@Param('uuid') id: string): Promise<Guest> {
帰ってこない　単純にエラーが起こってでそこの例外処理とかはモナカ次第

2022-10-06 14:29 UTC, re-taro requested changes
https://github.com/suzuka-kosen-festa/2022-server/blob/d47d620f6c645e1ae9c5ba545b79e0eb3537d178/src/student/student.controller.ts#L21-L28

ここについても`Promise<Student | null>`の可能性がないかどうか、Invalidな場合のレスポンスをください

2022-10-06 14:29 UTC, re-taro requested changes
https://github.com/suzuka-kosen-festa/2022-server/blob/d47d620f6c645e1ae9c5ba545b79e0eb3537d178/src/student/student.service.ts#L17-L23

ここも`Promise<Student | null>`なのではないか？

2022-10-06 14:29 UTC, Bayathy commented on src/health/health.e2e-spec.ts
> +import { Test, TestingModule } from '@nestjs/testing';
ごめん消し忘れか、一回分割してから戻す時に忘れてたわすまんの

2022-10-06 14:32 UTC, Bayathy commented on src/student/entities/student.ts
> +import { GuestEntity } from '../../guest/entity/guest';
おけ

2022-10-06 14:32 UTC, re-taro requested changes
e2e testのCIも追加して回してください(別PRで先にそっちをマージしてください)

2022-10-06 14:34 UTC, re-taro commented on src/guest/guest.controller.ts
> +   async checkuuid(@Param('uuid') id: string): Promise<Guest> {
そしたらこっちの対応をお願いします
https://github.com/suzuka-kosen-festa/2022-server/pull/33#discussion_r988465958

2022-10-06 14:42 UTC, Bayathy commented on src/health/health.e2e-spec.ts
> +   beforeEach(async () => {
app.e2eはインスタンス立ちまくるから元からbefore Allにしてると思う。ちなみにhealth checkはapp.e2eにまとめ忘れてるからこのファイルは消えます

2022-10-06 23:49 UTC, Bayathy commented on src/guest/guest.controller.ts
> +   async checkuuid(@Param('uuid') id: string): Promise<Guest> {
さーせんエラーが出るのは別のやつでこれはnullが帰ってきます

2022-10-07 05:06 UTC, re-taro commented on src/guest/guest.controller.ts
> +   async checkuuid(@Param('uuid') id: string): Promise<Guest> {
そしたら下のInvalid responseにnullが返ってくることを明記して型をnullにしてください

2022-10-07 14:58 UTC, re-taro approved these changes

2022-10-07 14:59 UTC, re-taro requested changes
approveしたけど全然e2e落ちてたわ

2022-10-08 04:55 UTC, re-taro approved these changes

2022-10-08 06:46 UTC, merged