admin Moduleと入場履歴関連のAPI
suzuka-kosen-festa/2022-server pull request #39
Opened 2022-10-15 12:45 UTC by Bayathy

ユニットテスト書く前に一旦レビューしてもらいたい

e2eは書いてます

2022-10-16 05:36 UTC, re-taro requested changes

2022-10-16 05:36 UTC, re-taro commented on src/admin/admin.controller.ts
> +   @Get('test')
消し忘れ

2022-10-16 05:36 UTC, re-taro commented on src/admin/admin.controller.ts
> +import { Controller, Get, Param } from '@nestjs/common';
Swaggerは後で書かれるという認識で良い？

2022-10-16 05:36 UTC, re-taro commented on src/admin/admin.controller.ts
> +   async exportStudentGuestId(): Promise<unknown> {
こいつらunknown返ってくるの嫌だな。型が不定なの？

2022-10-16 05:36 UTC, re-taro commented on src/admin/admin.module.ts
> +   providers: [AdminService, StudentService, GuestService, JhsService, ObService, SponsorService],
DIの仕方がおかしい気がする。今までのmoduleは見ていないからわからない確認したら下のツリーに報告する

```suggestion
   imports: [StudentsModule, GuestModule, JhsModule, ObModule, SponsorModule]
   providers: [AdminService],
```

2022-10-16 05:36 UTC, re-taro commented on src/history/history.controller.spec.ts
> +   beforeEach(async () => {
```suggestion
   beforeAll(async () => {
```

2022-10-16 05:36 UTC, re-taro commented on src/history/history.controller.ts
> +import { Controller, Get } from '@nestjs/common';
Swaggerは後から生えるということで？

2022-10-16 05:36 UTC, re-taro commented on src/history/history.service.spec.ts
> +   beforeEach(async () => {
```suggestion
   beforeAll(async () => {
```

2022-10-16 07:35 UTC, Bayathy commented on src/admin/admin.controller.ts
> +import { Controller, Get, Param } from '@nestjs/common';
普通に忘れてたから書いた

2022-10-16 07:40 UTC, Bayathy commented on src/admin/admin.controller.ts
> +   async exportStudentGuestId(): Promise<unknown> {
すまんー変更し忘れや

2022-10-16 14:20 UTC, Bayathy commented on src/history/history.controller.ts
> +import { Controller, Get } from '@nestjs/common';
[8aa6de6](https://github.com/suzuka-kosen-festa/2022-server/pull/39/commits/8aa6de664a3f1c6004ab628b8cfba79b8c1bf26a)

2022-10-16 14:20 UTC, Bayathy commented on src/admin/admin.controller.ts
> +import { Controller, Get, Param } from '@nestjs/common';
[4b82515](https://github.com/suzuka-kosen-festa/2022-server/pull/39/commits/4b82515cef7becb74e849ac2c92cc96a5febff63)

2022-10-16 14:21 UTC, Bayathy commented on src/admin/admin.controller.ts
> +   async exportStudentGuestId(): Promise<unknown> {
[dcc36a8](https://github.com/suzuka-kosen-festa/2022-server/pull/39/commits/dcc36a8187efe47192ebd9e5ae5123c44c4cfe85)

2022-10-17 00:57 UTC, re-taro requested changes

2022-10-17 00:57 UTC, re-taro commented on src/admin/admin.service.ts
> +   async parseUuid(reqUuid: string): Promise<Student | OB | Guest | JHStudent | Sponsor> {
これtypeが存在しなければerrorを投げるけどtypeは存在するけど見つからなかったって場合は想定されない？ここに渡される時点でどっかで保証がされているのなら対応する必要はないはず。

2022-10-17 00:57 UTC, re-taro commented on src/admin/admin.service.spec.ts
> +   beforeEach(async () => {
```suggestion
   beforeAll(async () => {
```

2022-10-17 00:57 UTC, re-taro commented on src/admin/types/types.ts
> +export type ExportStudentGuest = {
フォルダ名とファイル名が同じでtypes/にこれ以上ファイルの追加がないのならindex.tsで良い

2022-10-17 01:05 UTC, Bayathy commented on src/admin/admin.service.ts
> +   async parseUuid(reqUuid: string): Promise<Student | OB | Guest | JHStudent | Sponsor> {
対応する必要はあります

2022-10-17 07:42 UTC, Bayathy commented on src/admin/admin.service.ts
> +   async parseUuid(reqUuid: string): Promise<Student | OB | Guest | JHStudent | Sponsor> {
[903a703](https://github.com/suzuka-kosen-festa/2022-server/pull/39/commits/903a7037dfc337d27b7e6a604ad8594e68b24e9a)

2022-10-17 07:43 UTC, Bayathy commented on src/admin/types/types.ts
> +export type ExportStudentGuest = {
[aff8551](https://github.com/suzuka-kosen-festa/2022-server/pull/39/commits/aff85517d92d9c1213b4f56530a55cd2ea2809c8)

2022-10-17 12:49 UTC, re-taro approved these changes
無責任Approve

2022-10-17 12:51 UTC, merged